export type AssetClass = "etf" | "stock" | "crypto" | "bond" | "reit";
export type Region = "world" | "usa" | "europe" | "asia" | "emerging" | "global";
export type Sector = "tech" | "finance" | "health" | "energy" | "consumer" | "industrial" | "materials" | "telecom" | "utilities" | "realestate" | "luxury" | "defense" | "broad";

export interface AssetMeta {
  symbol: string;
  name: string;
  type: AssetClass;
  region: Region;
  sector: Sector;
  esg: boolean;
  ter?: number;
  isin?: string;
}

export const ASSET_UNIVERSE: AssetMeta[] = [
  // ETF MONDE
  { symbol:"IWDA.AS",  name:"iShares MSCI World",              type:"etf",   region:"world",    sector:"broad",      esg:false, ter:0.20, isin:"IE00B4L5Y983" },
  { symbol:"VWCE.DE",  name:"Vanguard All-World",              type:"etf",   region:"world",    sector:"broad",      esg:false, ter:0.22, isin:"IE00BK5BQT80" },
  { symbol:"SWRD.PA",  name:"SPDR MSCI World",                 type:"etf",   region:"world",    sector:"broad",      esg:false, ter:0.12 },
  { symbol:"XDWD.DE",  name:"Xtrackers MSCI World",            type:"etf",   region:"world",    sector:"broad",      esg:false, ter:0.19 },
  { symbol:"WSML.L",   name:"iShares MSCI World Small Cap",    type:"etf",   region:"world",    sector:"broad",      esg:false, ter:0.35 },
  { symbol:"SUSW.PA",  name:"iShares MSCI World ESG",          type:"etf",   region:"world",    sector:"broad",      esg:true,  ter:0.20, isin:"IE00BYX2JD69" },
  { symbol:"PAWD.PA",  name:"Amundi MSCI World SRI",           type:"etf",   region:"world",    sector:"broad",      esg:true,  ter:0.18 },
  // ETF USA
  { symbol:"CSPX.AS",  name:"iShares Core S&P 500",            type:"etf",   region:"usa",      sector:"broad",      esg:false, ter:0.07, isin:"IE00B5BMR087" },
  { symbol:"VUAA.PA",  name:"Vanguard S&P 500",                type:"etf",   region:"usa",      sector:"broad",      esg:false, ter:0.07 },
  { symbol:"EQQQ.DE",  name:"Invesco NASDAQ-100",              type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.30, isin:"IE0032077012" },
  { symbol:"SXRV.DE",  name:"iShares NASDAQ-100",              type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.33 },
  { symbol:"QDVE.DE",  name:"iShares S&P 500 IT",              type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.15, isin:"IE00B3RBWM25" },
  { symbol:"QDVH.DE",  name:"iShares S&P 500 Health",          type:"etf",   region:"usa",      sector:"health",     esg:false, ter:0.15 },
  { symbol:"XLK",      name:"Technology Select SPDR",          type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.10 },
  { symbol:"XLF",      name:"Financial Select SPDR",           type:"etf",   region:"usa",      sector:"finance",    esg:false, ter:0.10 },
  { symbol:"XLV",      name:"Health Care Select SPDR",         type:"etf",   region:"usa",      sector:"health",     esg:false, ter:0.10 },
  { symbol:"XLE",      name:"Energy Select SPDR",              type:"etf",   region:"usa",      sector:"energy",     esg:false, ter:0.10 },
  { symbol:"XLI",      name:"Industrial Select SPDR",          type:"etf",   region:"usa",      sector:"industrial", esg:false, ter:0.10 },
  { symbol:"SOXX",     name:"iShares Semiconductor ETF",       type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.35 },
  { symbol:"SMH",      name:"VanEck Semiconductor ETF",        type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.35 },
  // ETF EUROPE
  { symbol:"SXRT.DE",  name:"iShares Core EURO STOXX 50",      type:"etf",   region:"europe",   sector:"broad",      esg:false, ter:0.10 },
  { symbol:"EXW1.DE",  name:"iShares STOXX Europe 600",        type:"etf",   region:"europe",   sector:"broad",      esg:false, ter:0.20 },
  { symbol:"MEUD.PA",  name:"Amundi Euro Stoxx 50",            type:"etf",   region:"europe",   sector:"broad",      esg:false, ter:0.05 },
  { symbol:"LYPS.DE",  name:"Lyxor STOXX Europe 600",          type:"etf",   region:"europe",   sector:"broad",      esg:false, ter:0.07 },
  { symbol:"IESE.AS",  name:"iShares MSCI EMU ESG",            type:"etf",   region:"europe",   sector:"broad",      esg:true,  ter:0.20 },
  // ETF ASIE
  { symbol:"IJPA.AS",  name:"iShares Core MSCI Japan",         type:"etf",   region:"asia",     sector:"broad",      esg:false, ter:0.12 },
  { symbol:"CSCA.SW",  name:"iShares MSCI China",              type:"etf",   region:"asia",     sector:"broad",      esg:false, ter:0.40 },
  { symbol:"IBZL.L",   name:"iShares MSCI India",              type:"etf",   region:"asia",     sector:"broad",      esg:false, ter:0.65 },
  // ETF EMERGENTS
  { symbol:"PAEEM.PA", name:"Amundi MSCI Emerging Markets",    type:"etf",   region:"emerging", sector:"broad",      esg:false, ter:0.20, isin:"LU1681045370" },
  { symbol:"IEMM.L",   name:"iShares Core MSCI EM IMI",        type:"etf",   region:"emerging", sector:"broad",      esg:false, ter:0.18 },
  { symbol:"VFEM.AS",  name:"Vanguard FTSE Emerging Markets",  type:"etf",   region:"emerging", sector:"broad",      esg:false, ter:0.22 },
  { symbol:"EIMI.L",   name:"iShares MSCI EM ESG Enhanced",    type:"etf",   region:"emerging", sector:"broad",      esg:true,  ter:0.18 },
  // ETF OBLIGATIONS
  { symbol:"IBGL.AS",  name:"iShares Core Global Agg Bond",    type:"bond",  region:"global",   sector:"broad",      esg:false, ter:0.10 },
  { symbol:"AGGH.L",   name:"iShares Core Global Agg Hdg",     type:"bond",  region:"global",   sector:"broad",      esg:false, ter:0.10 },
  { symbol:"DBZB.DE",  name:"Xtrackers Euro Gov Bond",         type:"bond",  region:"europe",   sector:"broad",      esg:false, ter:0.15 },
  { symbol:"IUSB.DE",  name:"iShares US Aggregate Bond",       type:"bond",  region:"usa",      sector:"broad",      esg:false, ter:0.05 },
  { symbol:"IHYG.L",   name:"iShares EUR High Yield",          type:"bond",  region:"europe",   sector:"broad",      esg:false, ter:0.50 },
  { symbol:"TLT",      name:"iShares 20+ Year Treasury",       type:"bond",  region:"usa",      sector:"broad",      esg:false, ter:0.15 },
  { symbol:"HYG",      name:"iShares iBoxx High Yield",        type:"bond",  region:"usa",      sector:"broad",      esg:false, ter:0.48 },
  { symbol:"LQD",      name:"iShares iBoxx Invest. Grade",     type:"bond",  region:"usa",      sector:"broad",      esg:false, ter:0.14 },
  { symbol:"EMB",      name:"iShares J.P. Morgan EM Bond",     type:"bond",  region:"emerging", sector:"broad",      esg:false, ter:0.39 },
  // ETF IMMOBILIER
  { symbol:"EPRE.PA",  name:"FTSE EPRA Europe Real Estate",    type:"reit",  region:"europe",   sector:"realestate", esg:false, ter:0.40, isin:"FR0010686099" },
  { symbol:"IQQP.DE",  name:"iShares MSCI World REIT",         type:"reit",  region:"world",    sector:"realestate", esg:false, ter:0.59 },
  { symbol:"IUSP.L",   name:"iShares US Property Yield",       type:"reit",  region:"usa",      sector:"realestate", esg:false, ter:0.40 },
  // ETF MATIERES PREMIERES
  { symbol:"SGLD.L",   name:"Invesco Physical Gold",           type:"etf",   region:"global",   sector:"materials",  esg:false, ter:0.12 },
  { symbol:"CMOD.L",   name:"iShares Diversified Commodity",   type:"etf",   region:"global",   sector:"materials",  esg:false, ter:0.19 },
  // ETF THEMATIQUES
  { symbol:"BOTZ",     name:"Global X Robotics & AI",          type:"etf",   region:"world",    sector:"tech",       esg:false, ter:0.68 },
  { symbol:"ARKK",     name:"ARK Innovation ETF",              type:"etf",   region:"usa",      sector:"tech",       esg:false, ter:0.75 },
  { symbol:"ICLN",     name:"iShares Global Clean Energy",     type:"etf",   region:"world",    sector:"utilities",  esg:true,  ter:0.40 },
  { symbol:"DRIV",     name:"Global X Autonomous & EV",        type:"etf",   region:"world",    sector:"industrial", esg:true,  ter:0.68 },
  // USA - TECH
  { symbol:"AAPL",     name:"Apple",                           type:"stock", region:"usa",      sector:"tech",       esg:false, isin:"US0378331005" },
  { symbol:"MSFT",     name:"Microsoft",                       type:"stock", region:"usa",      sector:"tech",       esg:false, isin:"US5949181045" },
  { symbol:"NVDA",     name:"Nvidia",                          type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"AMZN",     name:"Amazon",                          type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"GOOGL",    name:"Alphabet",                        type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"META",     name:"Meta Platforms",                  type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"TSLA",     name:"Tesla",                           type:"stock", region:"usa",      sector:"industrial", esg:true  },
  { symbol:"AVGO",     name:"Broadcom",                        type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"AMD",      name:"AMD",                             type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"INTC",     name:"Intel",                           type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"QCOM",     name:"Qualcomm",                        type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"TXN",      name:"Texas Instruments",               type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"MU",       name:"Micron Technology",               type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"AMAT",     name:"Applied Materials",               type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"LRCX",     name:"Lam Research",                    type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"KLAC",     name:"KLA Corporation",                 type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"CRM",      name:"Salesforce",                      type:"stock", region:"usa",      sector:"tech",       esg:true  },
  { symbol:"ADBE",     name:"Adobe",                           type:"stock", region:"usa",      sector:"tech",       esg:true  },
  { symbol:"NFLX",     name:"Netflix",                         type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"NOW",      name:"ServiceNow",                      type:"stock", region:"usa",      sector:"tech",       esg:true  },
  { symbol:"SNOW",     name:"Snowflake",                       type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"DDOG",     name:"Datadog",                         type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"CRWD",     name:"CrowdStrike",                     type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"ZS",       name:"Zscaler",                         type:"stock", region:"usa",      sector:"tech",       esg:false },
  { symbol:"NET",      name:"Cloudflare",                      type:"stock", region:"usa",      sector:"tech",       esg:false },
  // USA - FINANCE
  { symbol:"JPM",      name:"JPMorgan Chase",                  type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"V",        name:"Visa",                            type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"MA",       name:"Mastercard",                      type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"GS",       name:"Goldman Sachs",                   type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"BRK-B",   name:"Berkshire Hathaway",              type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"MS",       name:"Morgan Stanley",                  type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"BAC",      name:"Bank of America",                 type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"BX",       name:"Blackstone",                      type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"SPGI",     name:"S&P Global",                      type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"MCO",      name:"Moody's",                         type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"PYPL",     name:"PayPal",                          type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"COIN",     name:"Coinbase",                        type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"SQ",       name:"Block",                           type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"CB",       name:"Chubb",                           type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"AON",      name:"Aon",                             type:"stock", region:"usa",      sector:"finance",    esg:false },
  // USA - SANTE
  { symbol:"UNH",      name:"UnitedHealth",                    type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"JNJ",      name:"Johnson & Johnson",               type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"LLY",      name:"Eli Lilly",                       type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"PFE",      name:"Pfizer",                          type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"MRK",      name:"Merck",                           type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"ABBV",     name:"AbbVie",                          type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"AMGN",     name:"Amgen",                           type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"GILD",     name:"Gilead Sciences",                 type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"REGN",     name:"Regeneron",                       type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"VRTX",     name:"Vertex Pharmaceuticals",          type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"MRNA",     name:"Moderna",                         type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"ISRG",     name:"Intuitive Surgical",              type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"TMO",      name:"Thermo Fisher Scientific",        type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"CI",       name:"Cigna",                           type:"stock", region:"usa",      sector:"health",     esg:false },
  { symbol:"HUM",      name:"Humana",                          type:"stock", region:"usa",      sector:"health",     esg:false },
  // USA - CONSOMMATION
  { symbol:"HD",       name:"Home Depot",                      type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"WMT",      name:"Walmart",                         type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"PG",       name:"Procter & Gamble",                type:"stock", region:"usa",      sector:"consumer",   esg:true  },
  { symbol:"KO",       name:"Coca-Cola",                       type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"PEP",      name:"PepsiCo",                         type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"COST",     name:"Costco",                          type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"MCD",      name:"McDonald's",                      type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"SBUX",     name:"Starbucks",                       type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"NKE",      name:"Nike",                            type:"stock", region:"usa",      sector:"consumer",   esg:true  },
  { symbol:"TGT",      name:"Target",                          type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"LOW",      name:"Lowe's",                          type:"stock", region:"usa",      sector:"consumer",   esg:false },
  { symbol:"DIS",      name:"Walt Disney",                     type:"stock", region:"usa",      sector:"consumer",   esg:false },
  // USA - ENERGIE
  { symbol:"XOM",      name:"ExxonMobil",                      type:"stock", region:"usa",      sector:"energy",     esg:false },
  { symbol:"CVX",      name:"Chevron",                         type:"stock", region:"usa",      sector:"energy",     esg:false },
  { symbol:"NEE",      name:"NextEra Energy",                  type:"stock", region:"usa",      sector:"utilities",  esg:true  },
  // USA - INDUSTRIEL / DEFENSE
  { symbol:"BA",       name:"Boeing",                          type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"GE",       name:"GE Aerospace",                    type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"CAT",      name:"Caterpillar",                     type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"HON",      name:"Honeywell",                       type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"UPS",      name:"UPS",                             type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"FDX",      name:"FedEx",                           type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"DE",       name:"John Deere",                      type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"RTX",      name:"RTX Corp",                        type:"stock", region:"usa",      sector:"defense",    esg:false },
  { symbol:"LMT",      name:"Lockheed Martin",                 type:"stock", region:"usa",      sector:"defense",    esg:false },
  { symbol:"GD",       name:"General Dynamics",                type:"stock", region:"usa",      sector:"defense",    esg:false },
  { symbol:"NOC",      name:"Northrop Grumman",                type:"stock", region:"usa",      sector:"defense",    esg:false },
  // USA - MATERIAUX / REITS
  { symbol:"LIN",      name:"Linde",                           type:"stock", region:"usa",      sector:"materials",  esg:true  },
  { symbol:"APD",      name:"Air Products",                    type:"stock", region:"usa",      sector:"materials",  esg:true  },
  { symbol:"ECL",      name:"Ecolab",                          type:"stock", region:"usa",      sector:"materials",  esg:true  },
  { symbol:"FCX",      name:"Freeport-McMoRan",                type:"stock", region:"usa",      sector:"materials",  esg:false },
  { symbol:"AMT",      name:"American Tower",                  type:"reit",  region:"usa",      sector:"realestate", esg:false },
  { symbol:"PLD",      name:"Prologis",                        type:"reit",  region:"usa",      sector:"realestate", esg:true  },
  { symbol:"EQIX",     name:"Equinix Data Centers",            type:"reit",  region:"usa",      sector:"realestate", esg:true  },
  { symbol:"DLR",      name:"Digital Realty Trust",            type:"reit",  region:"usa",      sector:"realestate", esg:true  },
  { symbol:"O",        name:"Realty Income",                   type:"reit",  region:"usa",      sector:"realestate", esg:false },
  // USA - TELECOM
  { symbol:"T",        name:"AT&T",                            type:"stock", region:"usa",      sector:"telecom",    esg:false },
  { symbol:"VZ",       name:"Verizon",                         type:"stock", region:"usa",      sector:"telecom",    esg:false },
  { symbol:"TMUS",     name:"T-Mobile US",                     type:"stock", region:"usa",      sector:"telecom",    esg:false },
  { symbol:"CMCSA",    name:"Comcast",                         type:"stock", region:"usa",      sector:"telecom",    esg:false },
  // CANADA
  { symbol:"SHOP.TO",  name:"Shopify",                         type:"stock", region:"usa",      sector:"tech",       esg:true  },
  { symbol:"RY.TO",    name:"Royal Bank of Canada",            type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"TD.TO",    name:"TD Bank",                         type:"stock", region:"usa",      sector:"finance",    esg:false },
  { symbol:"CNR.TO",   name:"Canadian National Railway",       type:"stock", region:"usa",      sector:"industrial", esg:false },
  { symbol:"ENB.TO",   name:"Enbridge",                        type:"stock", region:"usa",      sector:"energy",     esg:false },
  { symbol:"BAM.TO",   name:"Brookfield Asset Management",     type:"stock", region:"usa",      sector:"finance",    esg:true  },
  { symbol:"ABX.TO",   name:"Barrick Gold",                    type:"stock", region:"usa",      sector:"materials",  esg:false },
  // ROYAUME-UNI
  { symbol:"AZN.L",    name:"AstraZeneca",                     type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"GSK.L",    name:"GSK",                             type:"stock", region:"europe",   sector:"health",     esg:false },
  { symbol:"RIO.L",    name:"Rio Tinto",                       type:"stock", region:"europe",   sector:"materials",  esg:false },
  { symbol:"LSEG.L",   name:"London Stock Exchange",           type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"BA.L",     name:"BAE Systems",                     type:"stock", region:"europe",   sector:"defense",    esg:false },
  { symbol:"RR.L",     name:"Rolls-Royce",                     type:"stock", region:"europe",   sector:"industrial", esg:false },
  { symbol:"VOD.L",    name:"Vodafone",                        type:"stock", region:"europe",   sector:"telecom",    esg:false },
  { symbol:"REL.L",    name:"RELX",                            type:"stock", region:"europe",   sector:"tech",       esg:true  },
  { symbol:"NWG.L",    name:"NatWest Group",                   type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"LLOY.L",   name:"Lloyds Banking Group",            type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"NG.L",     name:"National Grid",                   type:"stock", region:"europe",   sector:"utilities",  esg:true  },
  // FRANCE
  { symbol:"MC.PA",    name:"LVMH",                            type:"stock", region:"europe",   sector:"luxury",     esg:false, isin:"FR0000121014" },
  { symbol:"RMS.PA",   name:"Hermes",                          type:"stock", region:"europe",   sector:"luxury",     esg:false },
  { symbol:"KER.PA",   name:"Kering",                          type:"stock", region:"europe",   sector:"luxury",     esg:true  },
  { symbol:"OR.PA",    name:"L Oreal",                         type:"stock", region:"europe",   sector:"consumer",   esg:true  },
  { symbol:"SU.PA",    name:"Schneider Electric",              type:"stock", region:"europe",   sector:"industrial", esg:true  },
  { symbol:"EL.PA",    name:"EssilorLuxottica",                type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"BN.PA",    name:"Danone",                          type:"stock", region:"europe",   sector:"consumer",   esg:true  },
  { symbol:"AIR.PA",   name:"Airbus",                          type:"stock", region:"europe",   sector:"defense",    esg:false, isin:"NL0000235190" },
  { symbol:"SAF.PA",   name:"Safran",                          type:"stock", region:"europe",   sector:"defense",    esg:false },
  { symbol:"PUB.PA",   name:"Publicis Groupe",                 type:"stock", region:"europe",   sector:"tech",       esg:false },
  { symbol:"ML.PA",    name:"Michelin",                        type:"stock", region:"europe",   sector:"industrial", esg:true  },
  { symbol:"RI.PA",    name:"Pernod Ricard",                   type:"stock", region:"europe",   sector:"consumer",   esg:false },
  { symbol:"SGO.PA",   name:"Saint-Gobain",                    type:"stock", region:"europe",   sector:"materials",  esg:false },
  { symbol:"ORA.PA",   name:"Orange",                          type:"stock", region:"europe",   sector:"telecom",    esg:false },
  { symbol:"STM.PA",   name:"STMicroelectronics",              type:"stock", region:"europe",   sector:"tech",       esg:false },
  { symbol:"BNP.PA",   name:"BNP Paribas",                     type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"ACA.PA",   name:"Credit Agricole",                 type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"TTE.PA",   name:"TotalEnergies",                   type:"stock", region:"europe",   sector:"energy",     esg:false },
  { symbol:"EDF.PA",   name:"EDF",                             type:"stock", region:"europe",   sector:"utilities",  esg:false },
  { symbol:"CS.PA",    name:"AXA",                             type:"stock", region:"europe",   sector:"finance",    esg:false },
  // ALLEMAGNE
  { symbol:"SAP.DE",   name:"SAP",                             type:"stock", region:"europe",   sector:"tech",       esg:true  },
  { symbol:"ASML.AS",  name:"ASML",                            type:"stock", region:"europe",   sector:"tech",       esg:false, isin:"NL0010273215" },
  { symbol:"ALV.DE",   name:"Allianz",                         type:"stock", region:"europe",   sector:"finance",    esg:true  },
  { symbol:"ADS.DE",   name:"Adidas",                          type:"stock", region:"europe",   sector:"consumer",   esg:true  },
  { symbol:"DTE.DE",   name:"Deutsche Telekom",                type:"stock", region:"europe",   sector:"telecom",    esg:false },
  { symbol:"IFX.DE",   name:"Infineon Technologies",           type:"stock", region:"europe",   sector:"tech",       esg:true  },
  { symbol:"SIE.DE",   name:"Siemens",                         type:"stock", region:"europe",   sector:"industrial", esg:true  },
  { symbol:"MUV2.DE",  name:"Munich Re",                       type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"RWE.DE",   name:"RWE",                             type:"stock", region:"europe",   sector:"utilities",  esg:true  },
  { symbol:"BAS.DE",   name:"BASF",                            type:"stock", region:"europe",   sector:"materials",  esg:false },
  { symbol:"MRK.DE",   name:"Merck KGaA",                      type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"DBK.DE",   name:"Deutsche Bank",                   type:"stock", region:"europe",   sector:"finance",    esg:false },
  // SUISSE
  { symbol:"NESN.SW",  name:"Nestle",                          type:"stock", region:"europe",   sector:"consumer",   esg:true  },
  { symbol:"ROG.SW",   name:"Roche",                           type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"NOVN.SW",  name:"Novartis",                        type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"NOVO-B.CO",name:"Novo Nordisk",                    type:"stock", region:"europe",   sector:"health",     esg:true,  isin:"DK0060534915" },
  { symbol:"CFR.SW",   name:"Richemont",                       type:"stock", region:"europe",   sector:"luxury",     esg:false },
  { symbol:"ZURN.SW",  name:"Zurich Insurance",                type:"stock", region:"europe",   sector:"finance",    esg:true  },
  { symbol:"ABBN.SW",  name:"ABB",                             type:"stock", region:"europe",   sector:"industrial", esg:true  },
  { symbol:"SIKA.SW",  name:"Sika",                            type:"stock", region:"europe",   sector:"materials",  esg:true  },
  { symbol:"LONN.SW",  name:"Lonza Group",                     type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"GIVN.SW",  name:"Givaudan",                        type:"stock", region:"europe",   sector:"materials",  esg:true  },
  // PAYS-BAS
  { symbol:"INGA.AS",  name:"ING Groep",                       type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"HEIA.AS",  name:"Heineken",                        type:"stock", region:"europe",   sector:"consumer",   esg:false },
  { symbol:"WKL.AS",   name:"Wolters Kluwer",                  type:"stock", region:"europe",   sector:"tech",       esg:true  },
  { symbol:"PHIA.AS",  name:"Philips",                         type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"ABN.AS",   name:"ABN AMRO",                        type:"stock", region:"europe",   sector:"finance",    esg:false },
  // SUEDE
  { symbol:"VOLV-B.ST",name:"Volvo AB",                        type:"stock", region:"europe",   sector:"industrial", esg:true  },
  { symbol:"ERIC-B.ST",name:"Ericsson",                        type:"stock", region:"europe",   sector:"tech",       esg:false },
  { symbol:"ATCO-A.ST",name:"Atlas Copco",                     type:"stock", region:"europe",   sector:"industrial", esg:true  },
  { symbol:"HM-B.ST",  name:"H&M",                             type:"stock", region:"europe",   sector:"consumer",   esg:true  },
  { symbol:"INVE-B.ST",name:"Investor AB",                     type:"stock", region:"europe",   sector:"finance",    esg:false },
  // NORVEGE / DANEMARK / FINLANDE
  { symbol:"EQNR.OL",  name:"Equinor",                         type:"stock", region:"europe",   sector:"energy",     esg:false },
  { symbol:"DNB.OL",   name:"DNB Bank",                        type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"DSV.CO",   name:"DSV Panalpina",                   type:"stock", region:"europe",   sector:"industrial", esg:false },
  { symbol:"ORSTED.CO",name:"Orsted",                          type:"stock", region:"europe",   sector:"utilities",  esg:true  },
  { symbol:"NESTE.HE", name:"Neste",                           type:"stock", region:"europe",   sector:"energy",     esg:true  },
  { symbol:"KNEBV.HE", name:"Kone",                            type:"stock", region:"europe",   sector:"industrial", esg:true  },
  // ITALIE / ESPAGNE
  { symbol:"ENI.MI",   name:"Eni",                             type:"stock", region:"europe",   sector:"energy",     esg:false },
  { symbol:"UCG.MI",   name:"UniCredit",                       type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"ISP.MI",   name:"Intesa Sanpaolo",                 type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"RACE.MI",  name:"Ferrari",                         type:"stock", region:"europe",   sector:"luxury",     esg:false },
  { symbol:"LDO.MI",   name:"Leonardo",                        type:"stock", region:"europe",   sector:"defense",    esg:false },
  { symbol:"SAN.MC",   name:"Banco Santander",                 type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"TEF.MC",   name:"Telefonica",                      type:"stock", region:"europe",   sector:"telecom",    esg:false },
  { symbol:"IBE.MC",   name:"Iberdrola",                       type:"stock", region:"europe",   sector:"utilities",  esg:true  },
  { symbol:"AMS.MC",   name:"Amadeus IT",                      type:"stock", region:"europe",   sector:"tech",       esg:true  },
  // POLOGNE / BELGIQUE / AUTRICHE / PORTUGAL
  { symbol:"PKN.WA",   name:"PKN Orlen",                       type:"stock", region:"europe",   sector:"energy",     esg:false },
  { symbol:"CDR.WA",   name:"CD Projekt",                      type:"stock", region:"europe",   sector:"tech",       esg:false },
  { symbol:"UCB.BR",   name:"UCB",                             type:"stock", region:"europe",   sector:"health",     esg:true  },
  { symbol:"COLR.BR",  name:"Colruyt",                         type:"stock", region:"europe",   sector:"consumer",   esg:true  },
  { symbol:"OMV.VI",   name:"OMV",                             type:"stock", region:"europe",   sector:"energy",     esg:false },
  { symbol:"EBS.VI",   name:"Erste Group Bank",                type:"stock", region:"europe",   sector:"finance",    esg:false },
  { symbol:"EDP.LS",   name:"EDP",                             type:"stock", region:"europe",   sector:"utilities",  esg:true  },
  { symbol:"JMT.LS",   name:"Jeronimo Martins",                type:"stock", region:"europe",   sector:"consumer",   esg:false },
  // JAPON
  { symbol:"7203.T",   name:"Toyota",                          type:"stock", region:"asia",     sector:"industrial", esg:false },
  { symbol:"6758.T",   name:"Sony",                            type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"7974.T",   name:"Nintendo",                        type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"9432.T",   name:"NTT",                             type:"stock", region:"asia",     sector:"telecom",    esg:false },
  { symbol:"8306.T",   name:"Mitsubishi UFJ Financial",        type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"9984.T",   name:"SoftBank Group",                  type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"8035.T",   name:"Tokyo Electron",                  type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"6861.T",   name:"Keyence",                         type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"6367.T",   name:"Daikin Industries",               type:"stock", region:"asia",     sector:"industrial", esg:true  },
  { symbol:"4519.T",   name:"Chugai Pharmaceutical",           type:"stock", region:"asia",     sector:"health",     esg:true  },
  { symbol:"6501.T",   name:"Hitachi",                         type:"stock", region:"asia",     sector:"industrial", esg:true  },
  // COREE DU SUD / TAIWAN
  { symbol:"005930.KS",name:"Samsung Electronics",             type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"000660.KS",name:"SK Hynix",                        type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"005380.KS",name:"Hyundai Motor",                   type:"stock", region:"asia",     sector:"industrial", esg:false },
  { symbol:"035420.KS",name:"NAVER",                           type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"051910.KS",name:"LG Chem",                         type:"stock", region:"asia",     sector:"materials",  esg:false },
  { symbol:"2330.TW",  name:"TSMC",                            type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"2454.TW",  name:"MediaTek",                        type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"2317.TW",  name:"Foxconn",                         type:"stock", region:"asia",     sector:"industrial", esg:false },
  // CHINE / HONG KONG
  { symbol:"9988.HK",  name:"Alibaba",                         type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"700.HK",   name:"Tencent",                         type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"3690.HK",  name:"Meituan",                         type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"9618.HK",  name:"JD.com",                          type:"stock", region:"asia",     sector:"consumer",   esg:false },
  { symbol:"0941.HK",  name:"China Mobile",                    type:"stock", region:"asia",     sector:"telecom",    esg:false },
  { symbol:"1299.HK",  name:"AIA Group",                       type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"BIDU",     name:"Baidu",                           type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"PDD",      name:"PDD Holdings",                    type:"stock", region:"asia",     sector:"consumer",   esg:false },
  // INDE
  { symbol:"TCS.NS",   name:"Tata Consultancy Services",       type:"stock", region:"asia",     sector:"tech",       esg:true  },
  { symbol:"INFY.NS",  name:"Infosys",                         type:"stock", region:"asia",     sector:"tech",       esg:true  },
  { symbol:"HDFCBANK.NS",name:"HDFC Bank",                     type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"BHARTIARTL.NS",name:"Bharti Airtel",               type:"stock", region:"asia",     sector:"telecom",    esg:false },
  { symbol:"WIPRO.NS", name:"Wipro",                           type:"stock", region:"asia",     sector:"tech",       esg:true  },
  { symbol:"LT.NS",    name:"Larsen Toubro",                   type:"stock", region:"asia",     sector:"industrial", esg:false },
  // AUSTRALIE
  { symbol:"BHP.AX",   name:"BHP Group",                       type:"stock", region:"world",    sector:"materials",  esg:false },
  { symbol:"CBA.AX",   name:"Commonwealth Bank",               type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"CSL.AX",   name:"CSL Limited",                     type:"stock", region:"asia",     sector:"health",     esg:true  },
  { symbol:"ANZ.AX",   name:"ANZ Bank",                        type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"WBC.AX",   name:"Westpac Banking",                 type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"MQG.AX",   name:"Macquarie Group",                 type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"FMG.AX",   name:"Fortescue Metals",                type:"stock", region:"asia",     sector:"materials",  esg:false },
  // SINGAPORE / ISRAEL
  { symbol:"D05.SI",   name:"DBS Group",                       type:"stock", region:"asia",     sector:"finance",    esg:true  },
  { symbol:"O39.SI",   name:"OCBC Bank",                       type:"stock", region:"asia",     sector:"finance",    esg:false },
  { symbol:"SEA",      name:"Sea Limited",                     type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"GRAB",     name:"Grab Holdings",                   type:"stock", region:"asia",     sector:"tech",       esg:false },
  { symbol:"CHKP",     name:"Check Point Software",            type:"stock", region:"world",    sector:"tech",       esg:false },
  { symbol:"NICE",     name:"NICE Systems",                    type:"stock", region:"world",    sector:"tech",       esg:false },
  { symbol:"CYBR",     name:"CyberArk Software",               type:"stock", region:"world",    sector:"tech",       esg:false },
  // BRESIL / MEXIQUE
  { symbol:"VALE3.SA", name:"Vale",                            type:"stock", region:"emerging", sector:"materials",  esg:false },
  { symbol:"PETR4.SA", name:"Petrobras",                       type:"stock", region:"emerging", sector:"energy",     esg:false },
  { symbol:"ITUB4.SA", name:"Itau Unibanco",                   type:"stock", region:"emerging", sector:"finance",    esg:false },
  { symbol:"WEGE3.SA", name:"WEG",                             type:"stock", region:"emerging", sector:"industrial", esg:true  },
  { symbol:"AMXL.MX",  name:"America Movil",                   type:"stock", region:"emerging", sector:"telecom",    esg:false },
  { symbol:"WALMEX.MX",name:"Walmart de Mexico",               type:"stock", region:"emerging", sector:"consumer",   esg:false },
  { symbol:"CX",       name:"Cemex",                           type:"stock", region:"emerging", sector:"materials",  esg:false },
  // ARABIE SAOUDITE / AFRIQUE DU SUD / INDONESIE
  { symbol:"2222.SR",  name:"Saudi Aramco",                    type:"stock", region:"emerging", sector:"energy",     esg:false },
  { symbol:"1180.SR",  name:"Al Rajhi Bank",                   type:"stock", region:"emerging", sector:"finance",    esg:false },
  { symbol:"NPSNY",    name:"Naspers",                         type:"stock", region:"emerging", sector:"tech",       esg:false },
  { symbol:"AGLXY",    name:"Anglo American",                  type:"stock", region:"world",    sector:"materials",  esg:false },
  { symbol:"BBCA.JK",  name:"Bank Central Asia",               type:"stock", region:"emerging", sector:"finance",    esg:false },
  { symbol:"TLKM.JK",  name:"Telkom Indonesia",                type:"stock", region:"emerging", sector:"telecom",    esg:false },
  // CRYPTO
  { symbol:"BTC-EUR",  name:"Bitcoin",                         type:"crypto",region:"global",   sector:"broad",      esg:false },
  { symbol:"ETH-EUR",  name:"Ethereum",                        type:"crypto",region:"global",   sector:"broad",      esg:false },
  { symbol:"SOL-EUR",  name:"Solana",                          type:"crypto",region:"global",   sector:"broad",      esg:false },
  { symbol:"BNB-EUR",  name:"BNB Binance",                     type:"crypto",region:"global",   sector:"broad",      esg:false },
  { symbol:"XRP-EUR",  name:"XRP",                             type:"crypto",region:"global",   sector:"broad",      esg:false },
  { symbol:"ADA-EUR",  name:"Cardano",                         type:"crypto",region:"global",   sector:"broad",      esg:true  },
  { symbol:"AVAX-EUR", name:"Avalanche",                       type:"crypto",region:"global",   sector:"broad",      esg:false },
  { symbol:"DOT-EUR",  name:"Polkadot",                        type:"crypto",region:"global",   sector:"broad",      esg:false },
];

export const UNIVERSE_COUNT = ASSET_UNIVERSE.length;
